log_level: info
keep_running: true
global:
  download_dir: out
  downloader_instance_num: 16
  get_videos: true
  get_photos: true
  tweet_amount: 1000
users:
  - username: BBCWorld
    tweet_amount: 100
    get_videos: false
  - username: wbpictures