name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: make build_all

      - name: Test
        run: |
          mv configs/config.example.yaml configs/config.yaml
          go test -cover ./... -race

      - name: Install git-chglog
        uses: craicoverflow/install-git-chglog@v1

      - name: Generate Changelog
        run: |
          git-chglog -o CHANGELOG.md

      - name: Zip
        run: |
          zip -r twitter-media-scraper.linux-amd64-${RELEASE_VERSION}.zip twitter-media-scraper.linux-amd64 configs
          zip -r twitter-media-scraper.linux-arm-${RELEASE_VERSION}.zip twitter-media-scraper.linux-arm configs
          zip -r twitter-media-scraper.linux-arm64-${RELEASE_VERSION}.zip twitter-media-scraper.linux-arm64 configs
          zip -r twitter-media-scraper.windows-amd64-${RELEASE_VERSION}.zip twitter-media-scraper.windows-amd64 configs
          zip -r twitter-media-scraper.darwin-amd64-${RELEASE_VERSION}.zip twitter-media-scraper.darwin-amd64 configs

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.RELEASE_UPLOAD_TOKEN }}
          files: |
            twitter-media-scraper.linux-amd64-${RELEASE_VERSION}.zip
            twitter-media-scraper.linux-arm-${RELEASE_VERSION}.zip
            twitter-media-scraper.linux-arm64-${RELEASE_VERSION}.zip
            twitter-media-scraper.windows-amd64-${RELEASE_VERSION}.zip
            twitter-media-scraper.darwin-amd64-${RELEASE_VERSION}.zip
        env:
          GITHUB_REPOSITORY: PetrusZ/twitter-media-scraper

      - name: Docker build and push to DockerHub
        env:
          REGISTRY: patrickz07
          REPOSITORY: simple-bank
        run: |
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u $REGISTRY --password-stdin
          docker build -t $REGISTRY/$REPOSITORY:$RELEASE_VERSION -t $REGISTRY/$REPOSITORY:latest .
          docker push -a $REGISTRY/$REPOSITORY
